version: "3.9"

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db/:/root/db/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db