# Generated by Django 3.2.7 on 2021-09-09 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do POP')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição do POP')),
                ('data_publicacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Publicação')),
                ('arquivo', models.FileField(upload_to='pop', verbose_name='Arquivo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departamentos', verbose_name='Departamento')),
            ],
        ),
    ]
