# Generated by Django 3.2.7 on 2021-09-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210909_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alvaras',
            name='arquivo',
            field=models.FileField(upload_to='alvaras_licencas', verbose_name='Arquivo'),
        ),
    ]
