# Generated by Django 3.2.7 on 2021-09-11 22:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_formulariopadrao_publicado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariopadrao',
            name='publicado_por',
        ),
        migrations.CreateModel(
            name='HistoricalFormularioPadrao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Formulário')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição do Formulário')),
                ('data_publicacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Publicação')),
                ('arquivo', models.TextField(max_length=100, verbose_name='Arquivo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('departamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.departamentos', verbose_name='Departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Formulário Padrão',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
