# Generated by Django 3.2.7 on 2021-09-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_utilitarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilitarios',
            options={'verbose_name': 'Utilitário TI', 'verbose_name_plural': 'Utilitários TI'},
        ),
    ]
